apiVersion: v1
kind: Service
metadata:
  name: actuation
spec:
  type: ClusterIP
  ports:
    - name: actuation
      port: 8000          # Port k8s svc will listen for incoming traffic within the k8s cluster
      targetPort: 8000    # Port of pod to route incoming traffic
      protocol: TCP
  selector:
    app: actuation
