apiVersion: v1
kind: Service
metadata:
  name: sif-edge
spec:
  type: NodePort          # A different type of Service type. `NodePort` enables
                          # services to be reachable from outside of the cluster by using
                          # the node's IP and the service's `nodePort`. Services
                          # within the cluster must use the `port` value when reaching it
  ports:
    - name: sif-edge
      port: 9000
      targetPort: 9000
      nodePort: 30032
      protocol: TCP       # You can also use UDP in case your service does not provide a ACK message (ACK is part of TCP protocol)
  selector:
    app: sif-edge
